baseURL = "/"
languageCode = "en-us"
theme = "paper"
themesDir = "themes"
title = "Aldo Borrero"
author = "Aldo Borrero"
paginate = 10

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'aldoborrero'
github = 'aldoborrero'
mastodon = 'https://fosstodon.org/@aldo'
rss = true

# home page profile
avatar = 'https://pbs.twimg.com/profile_images/1227915659599843329/4TEsb3Ya_400x400.jpg'
name = 'Aldo Borrero'
bio = 'Writer of Software · Open Source, Ethereum & Nix passionate'

# misc
disableHLJS = false
monoDarkIcon = true
